using Microsoft.EntityFrameworkCore;
using PurePrep.Server.Data;

namespace PurePrep.Server.Services;

/// <summary>
/// Decides how many free Smart Credits a brand-new device is entitled to.
///
/// Device ids are generated by the client and cannot be trusted, so "new device" is not by itself
/// evidence of a new user. This caps how many new devices one origin may be granted free credits
/// for per window; past the cap the device is still usable, it just starts empty.
/// </summary>
public interface IFreeCreditPolicy
{
    /// <summary>Free credits to seed <paramref name="deviceId"/> with. Zero when the origin is over its cap.</summary>
    Task<int> ResolveAsync(Guid deviceId, string? ipHash, CancellationToken ct = default);
}

public sealed class SqliteFreeCreditPolicy(IDbContextFactory<ServerDbContext> factory, CreditOptions options)
    : IFreeCreditPolicy
{
    public async Task<int> ResolveAsync(Guid deviceId, string? ipHash, CancellationToken ct = default)
    {
        // No determinable origin means the cap cannot be enforced, so the allowance is not given.
        // A real client always has one; this is the path taken by anonymising proxies and by
        // misconfigured forwarded-headers, and it must fail closed rather than open.
        if (string.IsNullOrEmpty(ipHash))
            return 0;

        await using var db = await factory.CreateDbContextAsync(ct);

        // Already seeded: answer consistently and never consume a second slot for the same device.
        var existing = await db.DeviceSeeds.AsNoTracking()
            .FirstOrDefaultAsync(x => x.DeviceId == deviceId, ct);
        if (existing is not null)
            return options.FreeCredits;

        var since = DateTimeOffset.UtcNow - options.NewDeviceWindow;
        var recent = await db.DeviceSeeds
            .CountAsync(x => x.IpHash == ipHash && x.SeededAt >= since, ct);
        if (recent >= options.MaxNewDevicesPerIpPerDay)
            return 0;

        db.DeviceSeeds.Add(new DeviceSeed
        {
            DeviceId = deviceId,
            IpHash = ipHash,
            SeededAt = DateTimeOffset.UtcNow,
        });

        try
        {
            await db.SaveChangesAsync(ct);
        }
        catch (DbUpdateException)
        {
            // A concurrent request seeded this same device first; the allowance is unchanged.
        }

        return options.FreeCredits;
    }
}
